baseurl = "http://apanzerj.github.io/"
languageCode = "en-us"
title = "PanzerSpeaks"
theme = "ghostwriter"

[Author]
    name = "Adam Panzer"
    profile = "https://google.com/+XXX"

[Taxonomies]
    tag = "tags"

[Params]
    intro = true
    headline = "All The Things"
    description = "If you are tired of listening to me talk, think of this as the cliff notes."
    github = "https://github.com/apanzerj"
    linkedin = "https://www.linkedin.com/in/apanzerj"
    twitter = "https://twitter.com/apanzerj"

[Permalinks]
    post = "/:year/:month/:day/:filename/"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Projects"
    url = "/project/"
    weight = 2

[[menu.main]]
    name = "Contact"
    url = "/page/contact/"
    weight = 3

[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 4
